
export default new Map([
["content/blog/welcome.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2Fwelcome.mdx&astroContentModuleFlag=true")],
["content/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Findex.mdx&astroContentModuleFlag=true")],
["content/blog/lorem_ipsum.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2Florem_ipsum.mdx&astroContentModuleFlag=true")],
["content/blog/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2Findex.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/blog.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2Fblog.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/docs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2Fdocs.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/getting-started/configuration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Fgetting-started%2Fconfiguration.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/routing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2Frouting.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/getting-started/project-structure.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Fgetting-started%2Fproject-structure.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/components/code-block.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2Fcomponents%2Fcode-block.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/getting-started/installation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Fgetting-started%2Finstallation.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/getting-started/getting-started.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Fgetting-started%2Fgetting-started.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/getting-started/deploy.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Fgetting-started%2Fdeploy.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/components/alert.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2Fcomponents%2Falert.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/_default.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2F_default.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/_default.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2F_default.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/components/_default.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2Fcomponents%2F_default.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/getting-started/_default.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Fgetting-started%2F_default.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/components/text.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2Fcomponents%2Ftext.mdx&astroContentModuleFlag=true")],
["content/docs/documentation/foundamentals/components/markdown.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fdocs%2Fdocumentation%2Ffoundamentals%2Fcomponents%2Fmarkdown.mdx&astroContentModuleFlag=true")]]);
		